# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

jobs:

# Job to Build the Browsers
- job: Cliqz_IOS_CI_Build
  timeoutInMinutes: 60
  strategy:
    matrix:
      Ghostery:
        brand: 'ghostery'
        scheme: 'Fennec'
        actions: 'clean build test'
        testbranch: 'azure-pipelines'
      Lumen:
        brand: 'lumen'
        scheme: 'Lumen'
        actions: 'clean build'
        testbranch: 'web-performance'
  pool:
    vmImage: 'macOS 10.13'

  steps:

  - script: pip install aws-cli
    displayName: "Install AWS CLI"

  - bash: |
      echo "AWS LS"
      aws s3 ls
      echo "\n\n\n\n AWS LS Specific Folder"
      aws s3 ls s3://cliqz-test-artifact-upload
    env:
      AWS_ACCESS_KEY_ID: $(aws.keyid)
      AWS_SECRET_ACCESS_KEY: $(aws.secret)
      AWS_DEFAULT_REGION: $(aws.region)
      AWS_DEFAULT_OUTPUT: text
    displayName: List AWS